### 2.Task 1.1 :Write a function to compute 5/0 and use try/except to catch the exceptions

In [1]:
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional Part as Answer 
        result = x // y 
        print(" Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 

In [2]:
divide(5,0)

Sorry ! You are dividing by zero 


In [3]:
divide(5,5)

 Your answer is : 1


### 2.Task 1.2 :Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]Hint: Subject,Verb and Object should be declared in the program as shown below.

In [13]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [11]:
for subject in subjects :
    for verb in verbs :
        for obj in objects:
            print('{} {} {}'.format(subject,verb,obj))
        

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [16]:
sentences=[(subject +" "+ verb +" " + obj) for subject in subjects for verb in verbs for obj in objects] 
for sentence in sentences: 
    print(sentence)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task 2.1 Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

In [17]:
import numpy as np
def out_matrix(in_vector):
    x = np.array(in_vector)
    N=len(x)
    '''
    Iterating through each element of the vector and applying exponential operation on each of the element with operand starting from 0 to n-1th element
    and populating the result in a 2D array. Finally applied Transpose function on the resultant 2D array to obtain the desired output with increasing geometric progression as per Vandermonde Matrix Theory
    '''
    #y = np.array([x**(N-i-1) for i in range(N)]) # Implementing Decreasing boolean argument
    y = np.array([x**i for i in range(N)])
    return(y.T)
in_vector = [1,4,5,7]
print(out_matrix(in_vector))

[[  1   1   1   1]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   7  49 343]]
